language: python
python:
  - "2.7"
# test environments
env:
  #For PyMOL 1.7
  - PYMOL_VER=1.7 PYMOL_LINK=https://sourceforge.net/projects/pymol/files/pymol/1.7/pymol-v1.7.6.0.tar.bz2 PYMOL_PREFIX=$PWD/tests/pymol/install PYMOL_MODULES=$PYMOL_PREFIX/tests/pymol/modules PYTHONPATH=$PYMOL_MODULES
  #For PyMOL 1.8
  - PYMOL_VER=1.8 PYMOL_LINK=https://sourceforge.net/projects/pymol/files/pymol/1.8/pymol-v1.8.6.0.tar.bz2 PYMOL_PREFIX=$PWD/tests/pymol/install PYMOL_MODULES=$PYMOL_PREFIX/tests/pymol/modules CPATH=$PWD/tests/pymol/msgpack-1.0.1/include PYTHONPATH=$PYMOL_MODULES
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libfreetype6-dev libpng12-dev
  #PyMOL dependencies
  - sudo apt-get install build-essential libglew-dev freeglut3-dev libxml2-dev libmsgpack-dev
  - wget PYMOL_LINK -P tests
  - tar -xvf tests/pymol*.tar.bz2 -C tests
  - if [[ PYMOL_VER == '1.8' ]]; then wget https://github.com/msgpack/msgpack-c/releases/download/cpp-1.0.1/msgpack-1.0.1.tar.gz -P tests/pymol
  - if [[ PYMOL_VER == '1.8' ]]; then tar -xvf tests/pymol/msgpack-1.0.1.tar.gz -C tests/pymol
install:
  - pip install -r requirements.txt
  #Build PyMOL
  - cd tests/pymol-1.8 ; python setup.py build install --home=$PYMOL_PREFIX --install-lib=$PYMOL_MODULES --install-scripts=$PYMOL_PREFIX
  - cd ../..
# command to run tests
script:
  - sh tests/run.sh
