# distribution
dist: xenial
# language
language: python
python:
  - "2.7"
# test environments
env:
  global:
    - PYMOL_PREFIX=/opt/pymol
    - PYMOL_MODULES=/opt/pymol/modules
    - PYTHONPATH=$PYMOL_MODULES
  matrix:
    #For PyMOL 1.8, GROMACS 2018
    - PYMOL_VER=1.8 PYMOL_PACKAGE=travisci-pymol-18 GROMACS_VER=2018.3 GROMACS_PACKAGE=travisci-gromacs-2018
# add ppa
addons:
  apt:
    sources:
      - ppa:makson96/dynamics
    packages:
    - travisci-pdb-files
    - $PYMOL_PACKAGE
    - $GROMACS_PACKAGE
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libfreetype6-dev libpng12-dev
install:
  - pip install -r tests/requirements.txt
# command to run tests
script:
  - sh tests/run.sh
